Repository AY2021S1-CS2103T-T15-4/tp, pull requests merged in 2020-10, with the labels that each got.

#100 Convert mock ui into code
  docs/UserGuide.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/cards/PersonCard.java
  src/main/java/seedu/address/ui/cards/PersonListPanel.java
  src/main/java/seedu/address/ui/display/CompanyDisplay.java
  src/main/java/seedu/address/ui/display/InformationDisplay.java
  src/main/java/seedu/address/ui/display/InternshipDisplay.java
  src/main/java/seedu/address/ui/display/TitleDescriptionDisplay.java
  src/main/java/seedu/address/ui/display/UserDisplay.java
  src/main/java/seedu/address/ui/tabs/TabName.java
  src/main/java/seedu/address/ui/tabs/Tabs.java
  src/main/java/seedu/address/ui/textstyle/TitleDescription.java
  src/main/resources/images/calendar.png
  src/main/resources/images/company.png
  src/main/resources/images/internship.png
  src/main/resources/images/sendarrow.png
  src/main/resources/images/user.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExitDialog.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/InformationDisplay.fxml
  src/main/resources/view/MainWindow.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/main/resources/view/Tabs.fxml
  src/main/resources/view/TitleDescriptionDisplay.fxml
Labels: type.Task

#98 Add Internship, Application and Item classes
  src/main/java/seedu/address/model/application/InternshipApplicationItem.java
  src/main/java/seedu/address/model/application/InternshipStatus.java
  src/main/java/seedu/address/model/application/StatusDate.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/model/internship/Wage.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/ItemList.java
  src/main/java/seedu/address/model/item/ReadOnlyItemList.java
  src/main/java/seedu/address/model/item/UniqueItemList.java
  src/main/java/seedu/address/model/item/exceptions/DuplicateItemException.java
  src/main/java/seedu/address/model/item/exceptions/ItemNotFoundException.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/util/DateUtil.java
  src/main/java/seedu/address/model/util/ItemUtil.java
  src/main/java/seedu/address/model/util/PositiveNumber.java
  src/main/java/seedu/address/model/util/StatusUtil.java
Labels: type.Epic

#97 Model user profile
  src/main/java/seedu/address/model/profile/Descriptor.java
  src/main/java/seedu/address/model/profile/ProfileItem.java
  src/main/java/seedu/address/model/profile/ProfileItemType.java
  src/main/java/seedu/address/model/util/ProfileItemTypeUtil.java
Labels: type.Task

#118 Add skeletal code for add and delete parser
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/add/AddCommand.java
  src/main/java/seedu/address/logic/commands/add/AddCommandAbstract.java
  src/main/java/seedu/address/logic/commands/add/AddInternshipCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCommandAbstract.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/clisyntax/ItemCliSyntax.java
  src/main/java/seedu/address/logic/parser/clisyntax/internship/InternshipCliSyntax.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/item/ItemListTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#124 Update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task

#125 Update user guide and developer guide for internship and application
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
Labels: priority.High, type.Task

#126 Fix naming issues and abstracted out classes with common regex
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/company/CompanyItem.java
  src/main/java/seedu/address/model/company/CompanyName.java
  src/main/java/seedu/address/model/company/Industry.java
  src/main/java/seedu/address/model/company/Name.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/model/internship/JobTitle.java
  src/main/java/seedu/address/model/internship/Period.java
  src/main/java/seedu/address/model/internship/Requirement.java
  src/main/java/seedu/address/model/internship/Wage.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/exceptions/DuplicateItemException.java
  src/main/java/seedu/address/model/profile/ProfileItem.java
  src/main/java/seedu/address/model/util/ItemUtil.java
  src/main/java/seedu/address/model/wrapper/AlphaNumericWord.java
  src/main/java/seedu/address/model/wrapper/NonEmptyString.java
  src/main/java/seedu/address/model/wrapper/PositiveNumber.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Task

#129 Update ug introduction
  docs/UserGuide.md
Labels: type.Task

#132 Include add application command and improve code quality
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/add/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/add/AddCommandAbstract.java
  src/main/java/seedu/address/logic/commands/add/AddInternshipCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/ApplicationParserUtil.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/add/AddUtil.java
  src/main/java/seedu/address/logic/parser/clisyntax/ApplicationCliSyntax.java
  src/main/java/seedu/address/logic/parser/clisyntax/ItemCliSyntax.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/application/Status.java
  src/main/java/seedu/address/model/application/StatusDate.java
  src/main/java/seedu/address/model/internship/Requirement.java
  src/main/java/seedu/address/model/util/DateUtil.java
  src/main/java/seedu/address/ui/tabs/TabName.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.High, type.Epic

#134 Refactor ui naming
  src/main/java/seedu/address/commons/util/TabUtil.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SwitchCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Tab.java
  src/main/java/seedu/address/model/TabManager.java
  src/main/java/seedu/address/model/tab/Tab.java
  src/main/java/seedu/address/model/tab/TabManager.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/cards/ApplicationCard.java
  src/main/java/seedu/address/ui/cards/Card.java
  src/main/java/seedu/address/ui/cards/ProfileCard.java
  src/main/java/seedu/address/ui/display/ApplicationDisplay.java
  src/main/java/seedu/address/ui/display/ProfileDisplay.java
  src/main/java/seedu/address/ui/display/TitleDescriptionDisplay.java
  src/main/java/seedu/address/ui/panel/ApplicationListPanel.java
  src/main/java/seedu/address/ui/panel/ProfileListPanel.java
  src/main/java/seedu/address/ui/tabs/TabName.java
  src/main/java/seedu/address/ui/tabs/Tabs.java
  src/main/resources/images/application.png
  src/main/resources/images/profile.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Tabs.fxml
  src/test/java/seedu/address/logic/commands/SwitchCommandTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: priority.High, type.Task

#140 Add delete commands for internship and application items
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/add/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteApplicationCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCommandAbstract.java
  src/main/java/seedu/address/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/parser/ApplicationParserUtil.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/delete/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/delete/DeleteInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/util/InternshipAccessor.java
  src/main/java/seedu/address/logic/parser/util/Util.java
  src/main/java/seedu/address/model/FilterableItemList.java
  src/main/java/seedu/address/model/ItemListManager.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/model/item/ItemList.java
  src/main/java/seedu/address/model/item/UniqueItemList.java
  src/main/java/seedu/address/model/util/StatusUtil.java
  src/main/java/seedu/address/ui/PanelDisplayKeyword.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
Labels: priority.High, type.Task

#143 Implement add company command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/add/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/add/AddCommandAbstract.java
  src/main/java/seedu/address/logic/commands/add/AddCompanyCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/logic/parser/CompanyParserUtil.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/add/AddCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/clisyntax/CompanyCliSyntax.java
  src/main/java/seedu/address/logic/parser/util/InternshipAccessor.java
  src/main/java/seedu/address/model/company/CompanyItem.java
  src/main/java/seedu/address/model/company/CompanyName.java
  src/main/java/seedu/address/model/company/Industry.java
Labels: priority.High, type.Task

#142 Add profile command
  src/main/java/seedu/address/logic/commands/add/AddInternshipCommand.java
  src/main/java/seedu/address/logic/commands/add/AddProfileCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/add/AddProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/clisyntax/InternshipCliSyntax.java
  src/main/java/seedu/address/logic/parser/clisyntax/ItemCliSyntax.java
  src/main/java/seedu/address/logic/parser/clisyntax/ProfileCliSyntax.java
  src/main/java/seedu/address/logic/parser/delete/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/util/ProfileParserUtil.java
  src/main/java/seedu/address/model/profile/Descriptor.java
  src/main/java/seedu/address/model/profile/ProfileItem.java
  src/main/java/seedu/address/model/profile/ProfileItemCategory.java
  src/main/java/seedu/address/model/profile/ProfileItemType.java
  src/main/java/seedu/address/model/profile/Title.java
  src/main/java/seedu/address/model/util/ProfileItemCategoryUtil.java
Labels: priority.High, type.Epic

#141 Update storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/MainAppUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/company/CompanyItem.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/model/internship/exceptions/InconsistentInternshipException.java
  src/main/java/seedu/address/model/item/Item.java
  src/main/java/seedu/address/model/item/exceptions/DuplicateItemException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/profile/ProfileItem.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonItemListStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableItemList.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/ListStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/application/JsonAdaptedApplicationItem.java
  src/main/java/seedu/address/storage/company/JsonAdaptedCompanyItem.java
  src/main/java/seedu/address/storage/company/JsonAdaptedIndustry.java
  src/main/java/seedu/address/storage/internship/JsonAdaptedInternshipItem.java
  src/main/java/seedu/address/storage/internship/JsonAdaptedRequirement.java
  src/main/java/seedu/address/storage/item/JsonAdaptedItem.java
  src/main/java/seedu/address/storage/person/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/person/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/profile/JsonAdaptedDescriptor.java
  src/main/java/seedu/address/storage/profile/JsonAdaptedProfileItem.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonItemListStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/person/JsonAdaptedPersonTest.java
Labels: priority.High, type.Story

#149 Implement delete company command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/add/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/add/AddCommandAbstract.java
  src/main/java/seedu/address/logic/commands/add/AddCompanyCommand.java
  src/main/java/seedu/address/logic/commands/add/AddInternshipCommand.java
  src/main/java/seedu/address/logic/commands/add/AddProfileCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteApplicationCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCommandAbstract.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCompanyCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/logic/parser/delete/DeleteCommandParser.java
  src/main/java/seedu/address/model/company/CompanyItem.java
  src/main/java/seedu/address/model/util/ItemUtil.java
Labels: priority.High, type.Task

#144 Linking class to ui
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/company/CompanyItem.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/model/profile/ProfileItem.java
  src/main/java/seedu/address/model/util/DateUtil.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PanelDisplayKeyword.java
  src/main/java/seedu/address/ui/TempStubData.java
  src/main/java/seedu/address/ui/cards/ApplicationCard.java
  src/main/java/seedu/address/ui/cards/Card.java
  src/main/java/seedu/address/ui/cards/CompanyCard.java
  src/main/java/seedu/address/ui/cards/LineNumber.java
  src/main/java/seedu/address/ui/cards/ProfileCard.java
  src/main/java/seedu/address/ui/display/ApplicationDisplay.java
  src/main/java/seedu/address/ui/display/CompanyDisplay.java
  src/main/java/seedu/address/ui/display/DisplayKeyList.java
  src/main/java/seedu/address/ui/display/InformationDisplay.java
  src/main/java/seedu/address/ui/display/ProfileDisplay.java
  src/main/java/seedu/address/ui/display/TitleDescriptionDisplay.java
  src/main/java/seedu/address/ui/panel/ApplicationListPanel.java
  src/main/java/seedu/address/ui/panel/CompanyListPanel.java
  src/main/java/seedu/address/ui/panel/ListPanel.java
  src/main/java/seedu/address/ui/panel/PanelDisplayKeyword.java
  src/main/java/seedu/address/ui/panel/ProfileListPanel.java
  src/main/java/seedu/address/ui/tabs/TabName.java
  src/main/java/seedu/address/ui/tabs/Tabs.java
  src/main/resources/images/achievement.png
  src/main/resources/images/experience.png
  src/main/resources/images/skills.png
  src/main/resources/view/Card.fxml
  src/main/resources/view/InformationDisplay.fxml
  src/main/resources/view/ListPanel.fxml
  src/main/resources/view/MainWindow.css
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/SwitchCommandTest.java
Labels: type.Task

#150 Delete profile command
  src/main/java/seedu/address/logic/commands/delete/DeleteProfileCommand.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/delete/DeleteCommandParser.java
Labels: priority.High, type.Task

#151 Add internship command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/add/AddInternshipCommand.java
  src/main/java/seedu/address/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/add/AddCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/util/ApplicationParserUtil.java
  src/main/java/seedu/address/logic/parser/util/CompanyParserUtil.java
  src/main/java/seedu/address/logic/parser/util/InternshipParserUtil.java
  src/main/java/seedu/address/logic/parser/util/ProfileParserUtil.java
  src/main/java/seedu/address/model/company/CompanyItem.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
Labels: priority.High, type.Task

#157 Link ui to update with model changes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/item/UniqueItemList.java
  src/main/java/seedu/address/model/view/View.java
  src/main/java/seedu/address/model/view/ViewManager.java
  src/main/java/seedu/address/storage/application/JsonAdaptedApplicationItem.java
  src/main/java/seedu/address/storage/profile/JsonAdaptedProfileItem.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TempStubData.java
  src/main/java/seedu/address/ui/cards/ApplicationCard.java
  src/main/java/seedu/address/ui/cards/CompanyCard.java
  src/main/java/seedu/address/ui/display/InformationDisplay.java
  src/main/java/seedu/address/ui/panel/ListPanel.java
  src/main/resources/view/MainWindow.css
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
Labels: type.Task

#153 Implement edit company command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/add/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/add/AddCompanyCommand.java
  src/main/java/seedu/address/logic/commands/add/AddInternshipCommand.java
  src/main/java/seedu/address/logic/commands/add/AddProfileCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCompanyCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommandAbstract.java
  src/main/java/seedu/address/logic/commands/edit/EditCompanyCommand.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/delete/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/edit/EditCompanyCommandParser.java
  src/main/java/seedu/address/model/company/CompanyItem.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
Labels: priority.High, type.Task

#154 Add Edit Command to User Profile
  src/main/java/seedu/address/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/address/logic/parser/edit/EditCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/edit/EditProfileCommandParser.java
  src/main/java/seedu/address/model/profile/ProfileItem.java
  src/main/java/seedu/address/storage/profile/JsonAdaptedProfileItem.java
  src/main/java/seedu/address/ui/cards/ProfileCard.java
Labels: priority.High, type.Task

#156 Add test cases for internship
  src/main/java/seedu/address/logic/parser/util/ApplicationParserUtil.java
  src/main/java/seedu/address/model/application/StatusDate.java
  src/main/java/seedu/address/model/util/DateUtil.java
  src/main/java/seedu/address/model/util/StatusUtil.java
  src/main/java/seedu/address/model/wrapper/AlphaNumericWord.java
  src/main/java/seedu/address/model/wrapper/NonEmptyString.java
  src/main/java/seedu/address/model/wrapper/PositiveNumber.java
  src/main/java/seedu/address/storage/application/JsonAdaptedApplicationItem.java
  src/test/java/seedu/address/model/internship/InternshipItemTest.java
  src/test/java/seedu/address/model/internship/InternshipItemUtil.java
  src/test/java/seedu/address/model/internship/JobTitleTest.java
  src/test/java/seedu/address/model/internship/PeriodTest.java
  src/test/java/seedu/address/model/internship/RequirementTest.java
  src/test/java/seedu/address/model/internship/WageTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/wrapper/AlphaNumericWordTest.java
  src/test/java/seedu/address/model/wrapper/NonEmptyStringTest.java
  src/test/java/seedu/address/model/wrapper/PositiveNumberTest.java
  src/test/java/seedu/address/storage/JsonItemListStorageTest.java
  src/test/java/seedu/address/testutil/InternshipItemBuilder.java
  src/test/java/seedu/address/testutil/SampleInternshipItems.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Task

#163 Implement edit internship command
  src/main/java/seedu/address/logic/commands/delete/DeleteCompanyCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteProfileCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditApplicationCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCompanyCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditInternshipCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/address/logic/parser/edit/EditApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/edit/EditCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditProfileCommandParser.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
Labels: priority.High, type.Task

#162 Update index and readme
  README.md
  docs/index.md
Labels: priority.High, type.Task

#165 Update readme.md and index.md header, userguide.md int commands
  README.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Task

#168 Profile test
  src/main/java/seedu/address/model/profile/Descriptor.java
  src/main/java/seedu/address/model/profile/ProfileItemCategory.java
  src/test/java/seedu/address/logic/commands/profile/ProfileCommandTestUtil.java
  src/test/java/seedu/address/model/profile/DescriptorTest.java
  src/test/java/seedu/address/model/profile/ProfileItemCategoryTest.java
  src/test/java/seedu/address/model/profile/ProfileItemTest.java
  src/test/java/seedu/address/model/profile/TitleTest.java
  src/test/java/seedu/address/testutil/profile/ProfileItemBuilder.java
  src/test/java/seedu/address/testutil/profile/SampleProfileItems.java
Labels: priority.Medium

#178 Add test cases
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/ui/GuardClauseUi.java
  src/main/java/seedu/address/ui/display/ApplicationDisplay.java
  src/main/java/seedu/address/ui/display/CompanyDisplay.java
  src/main/java/seedu/address/ui/display/ProfileDisplay.java
  src/main/java/seedu/address/ui/tabs/Tabs.java
  src/main/java/seedu/address/ui/textstyle/TitleDescription.java
  src/test/java/seedu/address/AppParametersTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/SwitchCommandTest.java
  src/test/java/seedu/address/logic/commands/util/CommandUtilTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/model/tab/TabManagerTest.java
  src/test/java/seedu/address/model/view/ViewManagerTest.java
  src/test/java/seedu/address/ui/GuardClauseUiTest.java
  src/test/java/seedu/address/ui/TitleDescriptionTest.java
  src/test/java/seedu/address/ui/UiPartTest.java
Labels: type.Task

#180 Update tests and add javadocs for Application, Internship, util, wrapper classes
  docs/team/johndoe.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/MainAppUtil.java
  src/main/java/seedu/address/commons/util/GeneralStringUtil.java
  src/main/java/seedu/address/commons/util/NumberUtil.java
  src/main/java/seedu/address/logic/commands/edit/EditApplicationCommand.java
  src/main/java/seedu/address/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/util/InternshipParserUtil.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/application/StatusDate.java
  src/main/java/seedu/address/model/company/Address.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/model/internship/JobTitle.java
  src/main/java/seedu/address/model/internship/Period.java
  src/main/java/seedu/address/model/internship/Requirement.java
  src/main/java/seedu/address/model/internship/Wage.java
  src/main/java/seedu/address/model/internship/exceptions/InconsistentInternshipException.java
  src/main/java/seedu/address/model/item/ItemList.java
  src/main/java/seedu/address/model/util/ApplicationItemUtil.java
  src/main/java/seedu/address/model/util/DateUtil.java
  src/main/java/seedu/address/model/util/InternshipItemUtil.java
  src/main/java/seedu/address/model/wrapper/AlphaNumericWord.java
  src/main/java/seedu/address/model/wrapper/NonEmptyString.java
  src/main/java/seedu/address/model/wrapper/PositiveNumber.java
  src/main/java/seedu/address/storage/company/JsonAdaptedCompanyItem.java
  src/main/java/seedu/address/storage/company/JsonAdaptedIndustry.java
  src/main/java/seedu/address/storage/internship/JsonAdaptedInternshipItem.java
  src/main/java/seedu/address/storage/internship/JsonAdaptedRequirement.java
  src/main/java/seedu/address/storage/profile/JsonAdaptedProfileItem.java
  src/test/java/seedu/address/model/application/ApplicationItemTest.java
  src/test/java/seedu/address/model/application/StatusDateTest.java
  src/test/java/seedu/address/model/application/StatusTest.java
  src/test/java/seedu/address/model/internship/InternshipItemTest.java
  src/test/java/seedu/address/model/internship/InternshipItemUtil.java
  src/test/java/seedu/address/model/internship/JobTitleTest.java
  src/test/java/seedu/address/model/internship/PeriodTest.java
  src/test/java/seedu/address/model/internship/RequirementTest.java
  src/test/java/seedu/address/model/internship/WageTest.java
  src/test/java/seedu/address/model/util/DateUtilTest.java
  src/test/java/seedu/address/storage/application/JsonAdaptedApplicationItemTest.java
  src/test/java/seedu/address/storage/internship/JsonAdaptedInternshipItemTest.java
  src/test/java/seedu/address/testutil/SampleApplicationItems.java
  src/test/java/seedu/address/testutil/SampleInternshipItems.java
  src/test/java/seedu/address/testutil/application/ApplicationItemBuilder.java
  src/test/java/seedu/address/testutil/application/ApplicationItemFieldsUtil.java
  src/test/java/seedu/address/testutil/application/SampleApplicationItems.java
  src/test/java/seedu/address/testutil/internship/InternshipItemBuilder.java
  src/test/java/seedu/address/testutil/internship/InternshipItemFieldsUtil.java
  src/test/java/seedu/address/testutil/internship/SampleInternshipItems.java
Labels: type.Task

#179 Update ui with javadocs
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/GuardClauseUi.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/UiPart.java
  src/main/java/seedu/address/ui/cards/ApplicationCard.java
  src/main/java/seedu/address/ui/cards/Card.java
  src/main/java/seedu/address/ui/cards/CompanyCard.java
  src/main/java/seedu/address/ui/cards/LineNumber.java
  src/main/java/seedu/address/ui/cards/ProfileCard.java
  src/main/java/seedu/address/ui/display/ApplicationDisplay.java
  src/main/java/seedu/address/ui/display/CompanyDisplay.java
  src/main/java/seedu/address/ui/display/DisplayKeyList.java
  src/main/java/seedu/address/ui/display/InformationDisplay.java
  src/main/java/seedu/address/ui/display/ProfileDisplay.java
  src/main/java/seedu/address/ui/display/TitleDescriptionDisplay.java
  src/main/java/seedu/address/ui/panel/ApplicationListPanel.java
  src/main/java/seedu/address/ui/panel/CompanyListPanel.java
  src/main/java/seedu/address/ui/panel/ListPanel.java
  src/main/java/seedu/address/ui/panel/PanelDisplayKeyword.java
  src/main/java/seedu/address/ui/panel/ProfileListPanel.java
  src/main/java/seedu/address/ui/tabs/Tabs.java
  src/main/java/seedu/address/ui/textstyle/TitleDescription.java
  src/main/resources/view/MainWindow.css
Labels: type.Task

#190 Skeleton for ListCommand and FindCommand
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/find/FindApplicationCommand.java
  src/main/java/seedu/address/logic/commands/find/FindCommand.java
  src/main/java/seedu/address/logic/commands/list/ListCommand.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/delete/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/list/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/switchparser/SwitchCommandParser.java
  src/main/java/seedu/address/logic/parser/util/GeneralParserUtil.java
  src/main/java/seedu/address/logic/parser/view/ViewCommandParser.java
  src/main/java/seedu/address/model/FilterableItemList.java
  src/main/java/seedu/address/model/application/ApplicationNameContainsKeyWordsPredicate.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
Labels: type.Task

#192 Add tests for parser util, Main Parser and Edit Application Parser
  src/main/java/seedu/address/commons/util/GeneralStringUtil.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/delete/DeleteInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/util/ApplicationParserUtil.java
  src/main/java/seedu/address/logic/parser/util/GeneralParserUtil.java
  src/main/java/seedu/address/model/application/Status.java
  src/main/java/seedu/address/model/application/StatusDate.java
  src/main/java/seedu/address/model/internship/Wage.java
  src/main/java/seedu/address/model/util/DateUtil.java
  src/main/java/seedu/address/model/wrapper/PositiveNumber.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/util/application/ApplicationCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/util/internship/InternshipCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/edit/EditApplicationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/util/ApplicationParserUtilTest.java
  src/test/java/seedu/address/logic/parser/util/GeneralParserUtilTest.java
  src/test/java/seedu/address/model/application/ApplicationItemTest.java
  src/test/java/seedu/address/model/application/StatusDateTest.java
  src/test/java/seedu/address/model/application/StatusTest.java
  src/test/java/seedu/address/model/internship/JobTitleTest.java
  src/test/java/seedu/address/model/internship/PeriodTest.java
  src/test/java/seedu/address/model/internship/RequirementTest.java
  src/test/java/seedu/address/model/internship/WageTest.java
  src/test/java/seedu/address/model/util/DateUtilTest.java
  src/test/java/seedu/address/model/wrapper/PositiveNumberTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/application/ApplicationItemBuilder.java
  src/test/java/seedu/address/testutil/application/ApplicationItemFieldsUtil.java
  src/test/java/seedu/address/testutil/application/EditApplicationDescriptorBuilder.java
  src/test/java/seedu/address/testutil/application/SampleApplicationItems.java
  src/test/java/seedu/address/testutil/internship/InternshipItemFieldsUtil.java
Labels: priority.High, type.Task

#197 Add argument validity checks to all commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/delete/DeleteInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/util/GeneralParserUtil.java
  src/test/java/seedu/address/logic/parser/edit/EditApplicationCommandParserTest.java
Labels: priority.High, type.bug

#199 Add individual parsers for delete and view com commands
  src/main/java/seedu/address/logic/parser/delete/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/delete/DeleteCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/delete/DeleteInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/util/GeneralParserUtil.java
  src/main/java/seedu/address/logic/parser/view/ViewCommandParser.java
  src/main/java/seedu/address/logic/parser/view/ViewCompanyCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#202 Add more methods to Model interface
  docs/diagrams/DeleteCompanyCommandClassDiagram.puml
  docs/diagrams/DeleteCompanyCommandSequenceDiagramPart1.puml
  docs/diagrams/DeleteCompanyCommandSequenceDiagramPart2.puml
  docs/diagrams/InternHunterStyle.puml
  docs/images/DeleteCompanyCommandClassDiagram.png
  docs/images/DeleteCompanyCommandSequenceDiagramPart1.png
  docs/images/DeleteCompanyCommandSequenceDiagramPart2.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/add/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/add/AddCompanyCommand.java
  src/main/java/seedu/address/logic/commands/add/AddProfileCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteApplicationCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCompanyCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteProfileCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditApplicationCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCompanyCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditInternshipCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/address/logic/commands/find/FindApplicationCommand.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/logic/commands/view/ViewApplicationCommand.java
  src/main/java/seedu/address/logic/commands/view/ViewCompanyCommand.java
  src/main/java/seedu/address/logic/commands/view/ViewProfileCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/wrapper/NonEmptyString.java
  src/main/java/seedu/address/storage/company/JsonAdaptedCompanyItem.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#201 Add esc keystroke to close help command
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: priority.High, type.Enhancement

#203 Add test cases for add and edit parsers
  src/main/java/seedu/address/logic/commands/add/AddProfileCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/address/logic/parser/add/AddProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/clisyntax/ProfileCliSyntax.java
  src/main/java/seedu/address/logic/parser/edit/EditProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/util/ProfileParserUtil.java
  src/main/java/seedu/address/model/profile/Descriptor.java
  src/main/java/seedu/address/model/profile/ProfileItemCategory.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/profile/ProfileCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/util/application/ApplicationCommandTestUtil.java
  src/test/java/seedu/address/logic/commands/util/profile/ProfileCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/add/AddProfileCommandParserTest.java
  src/test/java/seedu/address/logic/parser/edit/EditProfileCommandParserTest.java
  src/test/java/seedu/address/model/profile/DescriptorTest.java
  src/test/java/seedu/address/model/profile/ProfileItemCategoryTest.java
  src/test/java/seedu/address/model/profile/ProfileItemTest.java
  src/test/java/seedu/address/testutil/profile/EditProfileItemDescriptorBuilder.java
  src/test/java/seedu/address/testutil/profile/ProfileItemBuilder.java
  src/test/java/seedu/address/testutil/profile/SampleProfileItems.java
Labels: priority.Medium, type.Task

#207 User guide update
  docs/UserGuide.md
Labels: priority.Medium, type.Enhancement

#216 Update Edit Profile Command in DG
  docs/DeveloperGuide.md
  docs/diagrams/EditProfileCommandSequenceDiagram.puml
  docs/diagrams/EditprofileCommandSequenceDiagramSimplified.puml
  docs/diagrams/ExecuteEditMeCommand.puml
  docs/diagrams/ExecuteEditMeCommandAlt.puml
  docs/images/EditProfileCommandSequenceDiagram.png
  docs/images/EditProfileCommandSequenceDiagramSimplified.png
  docs/images/ExecuteEditMeCommand.png
  docs/images/ExecuteEditMeCommandAlt.png
  src/main/java/seedu/address/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/edit/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/edit/EditProfileCommandParser.java
  src/main/java/seedu/address/model/FilterableItemList.java
  src/main/java/seedu/address/model/ItemListManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: priority.High, type.Task

#206 Add view and delete command parsers
  src/main/java/seedu/address/logic/parser/delete/DeleteApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/delete/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/view/ViewApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/view/ViewCommandParser.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High, type.Task

#214 Add Command implementation in Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddApplicationCommandActivityDiagram.puml
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/CommandClassDiagram.puml
  docs/images/AddApplicationCommandActivityDiagram.png
  docs/images/AddCommandActivityDiagram.png
  docs/images/CommandClassDiagram.png
Labels: priority.High, type.Task

#215 Update switch command for Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ExecuteSwitchMeCommandSequenceDiagram.puml
  docs/diagrams/GetCommandResultSequenceDiagram.puml
  docs/diagrams/GetDeleteCommandResultSequenceDiagram.puml
  docs/diagrams/HandleDeleteDisplaySwitchIndexSequenceDiagram.puml
  docs/diagrams/SwitchCommandActivityDiagram.puml
  docs/diagrams/SwitchCommandClassDiagram.puml
  docs/diagrams/SwitchCommandSequenceDiagram.puml
  docs/images/ExecuteSwitchMeCommandSequenceDiagram.png
  docs/images/GetCommandResultSequenceDiagram.png
  docs/images/GetDeleteCommandResultSequenceDiagram.png
  docs/images/HandleDeleteDisplaySwitchIndexSequenceDiagram.png
  docs/images/SwitchCommandActivityDiagram.png
  docs/images/SwitchCommandClassDiagram.png
  docs/images/SwitchCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
Labels: priority.High, type.Task

#198 List and Find Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/GeneralStringUtil.java
  src/main/java/seedu/address/commons/util/TabUtil.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/SwitchCommand.java
  src/main/java/seedu/address/logic/commands/find/FindApplicationCommand.java
  src/main/java/seedu/address/logic/commands/find/FindCommand.java
  src/main/java/seedu/address/logic/commands/list/ListApplicationCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/list/ListCommandParser.java
  src/main/java/seedu/address/logic/parser/switchparser/SwitchCommandParser.java
  src/main/java/seedu/address/logic/parser/util/GeneralParserUtil.java
  src/main/java/seedu/address/logic/parser/util/TabParserUtil.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/ui/display/CompanyDisplay.java
  src/main/java/seedu/address/ui/display/InformationDisplay.java
  src/main/java/seedu/address/ui/display/ProfileDisplay.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/find/FindApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/list/ListApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/util/internship/InternshipCommandTestUtil.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/logic/parser/SwitchCommandParserTest.java
  src/test/java/seedu/address/logic/parser/edit/EditApplicationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/find/FindApplicationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/find/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/list/ListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/util/ApplicationParserUtilTest.java
  src/test/java/seedu/address/model/application/ApplicationItemTest.java
  src/test/java/seedu/address/model/internship/InternshipItemTest.java
Labels: priority.High, type.Task

#219 Update command class image in developer guide
  docs/images/CommandClassDiagram.png
Labels: priority.High, type.Task

#217 Add match command
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/commons/util/NumberUtil.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/model/FilterableItemList.java
  src/main/java/seedu/address/model/ItemListManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/model/profile/ProfileItem.java
  src/main/java/seedu/address/ui/ExitDialog.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/InternshipsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PopupWindow.java
  src/main/resources/view/InternshipsWindow.fxml
  src/main/resources/view/MainWindow.css
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/logic/parser/add/AddApplicationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/add/AddProfileCommandParserTest.java
  src/test/java/seedu/address/logic/parser/edit/EditApplicationCommandParserTest.java
  src/test/java/seedu/address/model/application/ApplicationItemTest.java
  src/test/java/seedu/address/model/internship/InternshipItemTest.java
Labels: priority.High, type.Task

#248 Refactor Json adapted item files
  docs/diagrams/DeleteCompanyCommandClassDiagram.puml
  docs/diagrams/InternHunterStyle.puml
  docs/diagrams/JsonAdaptedItemClassDiagram.puml
  docs/images/JsonAdaptedItemClassDiagram.png
  src/main/java/seedu/address/model/company/CompanyItem.java
  src/main/java/seedu/address/model/util/CompanyItemUtil.java
  src/main/java/seedu/address/storage/company/JsonAdaptedCompanyItem.java
  src/main/java/seedu/address/storage/internship/JsonAdaptedInternshipItem.java
  src/main/java/seedu/address/storage/profile/JsonAdaptedProfileItem.java
Labels: priority.High

#220 Add delete command parser tests for Application and Internship
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/MainParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/add/AddCommandParserWrapper.java
  src/main/java/seedu/address/logic/parser/delete/DeleteApplicationCommandParser.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/model/internship/Wage.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delete/DeleteApplicationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/delete/DeleteInternshipCommandParserTest.java
Labels: priority.High, type.Task

#249 Abstract out code in edit command
  src/main/java/seedu/address/logic/commands/edit/EditApplicationCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCompanyCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditInternshipCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/address/model/ItemListManager.java
Labels: priority.High, type.Task

#252 Implement find and list company commands and update UG
  docs/UserGuide.md
  docs/images/AddCompanySS.PNG
  docs/images/EditCompanySS.PNG
  docs/images/FindCompanyGoogleFacebookSS.PNG
  docs/images/FindCompanyGoogleSS.PNG
  docs/images/FindCompanyOneSS.PNG
  docs/images/OneCompanyInListSS.PNG
  docs/images/ViewComOneSS.PNG
  docs/images/ViewComTwoSS.PNG
  src/main/java/seedu/address/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/commands/find/FindApplicationCommand.java
  src/main/java/seedu/address/logic/commands/find/FindCommand.java
  src/main/java/seedu/address/logic/commands/find/FindCompanyCommand.java
  src/main/java/seedu/address/logic/commands/list/ListCommand.java
  src/main/java/seedu/address/logic/commands/list/ListCompanyCommand.java
  src/main/java/seedu/address/logic/parser/find/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindCompanyCommandParser.java
  src/main/java/seedu/address/logic/parser/list/ListCommandParser.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/application/ApplicationNameContainsKeyWordsPredicate.java
  src/main/java/seedu/address/model/company/CompanyNameContainsKeyWordsPredicate.java
  src/main/java/seedu/address/storage/application/JsonAdaptedApplicationItem.java
  src/test/java/seedu/address/logic/parser/find/FindCommandParserTest.java
Labels: User guide, priority.High, type.Task

#251 Fix DG errors and some code quality
  docs/DeveloperGuide.md
  docs/diagrams/GetCommandResultSequenceDiagram.puml
  docs/diagrams/GetDeleteCommandResultSequenceDiagram.puml
  docs/diagrams/HandleDeleteDisplaySwitchIndexSequenceDiagram.puml
  docs/diagrams/SwitchCommandSequenceDiagram.puml
  docs/images/GetCommandResultSequenceDiagram.png
  docs/images/GetDeleteCommandResultSequenceDiagram.png
  docs/images/HandleDeleteDisplaySwitchIndexSequenceDiagram.png
  docs/images/SwitchCommandSequenceDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/tab/TabManager.java
  src/main/java/seedu/address/model/view/ViewManager.java
  src/main/java/seedu/address/ui/ExitDialog.java
  src/main/java/seedu/address/ui/GuardClauseUi.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/cards/Card.java
  src/main/java/seedu/address/ui/display/DisplayKeyList.java
  src/main/java/seedu/address/ui/display/TitleDescriptionDisplay.java
  src/main/java/seedu/address/ui/panel/ApplicationListPanel.java
  src/main/java/seedu/address/ui/panel/CompanyListPanel.java
  src/main/java/seedu/address/ui/panel/ProfileListPanel.java
  src/main/java/seedu/address/ui/tabs/Tabs.java
  src/main/java/seedu/address/ui/textstyle/TitleDescription.java
Labels: Developer Guide

#253 Add Find and List command for profile
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/address/logic/commands/find/FindApplicationCommand.java
  src/main/java/seedu/address/logic/commands/find/FindCompanyCommand.java
  src/main/java/seedu/address/logic/commands/find/FindProfileCommand.java
  src/main/java/seedu/address/logic/commands/list/ListCommand.java
  src/main/java/seedu/address/logic/commands/list/ListProfileCommand.java
  src/main/java/seedu/address/logic/parser/find/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/find/FindProfileCommandParser.java
  src/main/java/seedu/address/logic/parser/list/ListCommandParser.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/profile/ProfileItemContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/find/FindProfileCommandTest.java
  src/test/java/seedu/address/logic/commands/list/ListApplicationCommandTest.java
  src/test/java/seedu/address/logic/commands/list/ListProfileCommandTest.java
  src/test/java/seedu/address/logic/parser/find/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/find/FindProfileCommandParserTest.java
Labels: priority.High, type.Story

#257 Update ug and dg and readme
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SwitchCommandActivityDiagram.puml
  docs/diagrams/SwitchCommandClassDiagram.puml
  docs/images/App.png
  docs/images/GuiAnnotated.png
  docs/images/Profile.png
  docs/images/SwitchCommandActivityDiagram.png
  docs/images/SwitchCommandClassDiagram.png
  docs/images/Ui.png
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/InternHunterLogo.png
Labels: Developer Guide, User guide

#261 Update application and match command in user guide
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/about-us-images/keanecjy.png
  docs/images/about-us-images/orzymandias.png
  docs/images/about-us-images/seanjyjy.png
  docs/images/about-us-images/shawn-nyk.png
  docs/images/about-us-images/zoroarkdarkrai.png
  docs/images/ug-application/AddApplication.png
  docs/images/ug-application/EditApplication.png
  docs/images/ug-application/FindApplication.png
  docs/images/ug-application/Internship.png
  docs/images/ug-application/MatchCommand.png
  docs/images/ug-application/ViewApplication.png
  src/main/resources/view/MainWindow.css
Labels: User guide

#260 Update User Guide for user profile
  docs/UserGuide.md
  docs/images/AddProfileItemSS.png
  docs/images/EditProfile.PNG
  docs/images/EditProfileItemAfterSS.png
  docs/images/EditProfileItemBeforeSS.png
  docs/images/FindProfileAfterSS.png
  docs/images/FindProfileAfterSSDouble.png
  docs/images/FindProfileBeforeSS.png
  docs/images/FindProfileDouble.png
  docs/images/FindProfileSingle.png
  docs/images/ViewProfile.png
  docs/images/ViewProfileAfterSS.png
  docs/images/ViewProfileBeforeSS.png
  docs/images/achievement.png
  docs/images/experience.png
  docs/images/skills.png
Labels: User guide, priority.High

#258 Update guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ClearCommandSequenceDiagram
  docs/diagrams/SampleDataActivityDiagram.puml
  docs/diagrams/SavingDataSequenceDiagram
  docs/images/AddInternship.png
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/EditInternship.png
  docs/images/EditInternshipApplication.png
  docs/images/SampleDataActivityDiagram.png
  docs/images/SavingDataSequenceDiagram.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/person/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/person/JsonAdaptedTag.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/person/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/storage/person/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/person/JsonSerializableAddressBookTest.java
Labels: Developer Guide, User guide

#269 Update view and edit in user guide
  docs/UserGuide.md
  docs/images/ug-application/EditApplication.png
  docs/images/ug-application/ViewApplication.png
  docs/images/ug-application/ViewApplication2.png
Labels: User guide

#271 Update images in UG
  docs/UserGuide.md
  docs/images/AddProfileItem.png
  docs/images/EditProfile.PNG
  docs/images/ViewProfile.png
Labels: User guide

#272 Remove deprecated tests
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/application/ApplicationItem.java
  src/main/java/seedu/address/model/internship/InternshipItem.java
  src/main/java/seedu/address/ui/InternshipsWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.High, type.Task

#273 Test cases
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/find/FindApplicationCommand.java
  src/main/java/seedu/address/logic/commands/find/FindCommand.java
  src/main/java/seedu/address/logic/commands/list/ListApplicationCommand.java
  src/main/java/seedu/address/logic/commands/list/ListCommand.java
  src/test/java/seedu/address/logic/parser/MainParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/ui/GuardClauseUiTest.java
Labels: priority.High, type.Task

#277 add Gui for match command
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/findAlexDavidResult.png
  docs/images/switchcommand/SwitchCommandActivityDiagram.png
  docs/images/switchcommand/SwitchCommandClassDiagram.png
  docs/images/switchcommand/SwitchCommandSequenceDiagram.png
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/MatchCommand.java
  src/main/java/seedu/address/ui/ExitDialog.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/cards/ApplicationCard.java
  src/main/java/seedu/address/ui/cards/CompanyCard.java
  src/main/java/seedu/address/ui/cards/InternshipCard.java
  src/main/java/seedu/address/ui/cards/ProfileCard.java
  src/main/java/seedu/address/ui/display/InformationDisplay.java
  src/main/java/seedu/address/ui/panel/InternshipListPanel.java
  src/main/java/seedu/address/ui/panel/ListPanel.java
  src/main/java/seedu/address/ui/popupwindow/HelpWindow.java
  src/main/java/seedu/address/ui/popupwindow/InternshipsWindow.java
  src/main/java/seedu/address/ui/popupwindow/PopupWindow.java
  src/main/java/seedu/address/ui/tabs/Tabs.java
  src/main/resources/view/InternshipsWindow.fxml
  src/main/resources/view/Tabs.fxml
Labels: type.Enhancement

#256 Refactor Use Cases for DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditProfileCommandSequenceDiagramSimplified.puml
  docs/images/EditProfileCommandSequenceDiagramSimplified.png
  docs/images/dg-profile/EditProfileCommandSequenceDiagram.png
  docs/images/dg-profile/EditProfileCommandSequenceDiagramSimplified.png
  docs/images/dg-profile/ExecuteEditMeCommand.png
  docs/images/dg-profile/ExecuteEditMeCommandAlt.png
  docs/images/ug-profile/AddProfileItem.png
  docs/images/ug-profile/AddProfileItemSS.png
  docs/images/ug-profile/EditProfile.PNG
  docs/images/ug-profile/EditProfileItemAfterSS.png
  docs/images/ug-profile/EditProfileItemBeforeSS.png
  docs/images/ug-profile/FindProfileAfterSS.png
  docs/images/ug-profile/FindProfileAfterSSDouble.png
  docs/images/ug-profile/FindProfileBeforeSS.png
  docs/images/ug-profile/FindProfileDouble.png
  docs/images/ug-profile/FindProfileSingle.png
  docs/images/ug-profile/Profile.png
  docs/images/ug-profile/ViewProfile.png
  docs/images/ug-profile/ViewProfileAfterSS.png
  docs/images/ug-profile/ViewProfileBeforeSS.png
  docs/images/ug-profile/achievement.png
  docs/images/ug-profile/experience.png
  src/main/java/seedu/address/logic/parser/edit/EditProfileCommandParser.java
Labels: Developer Guide, priority.High, type.Task

#276 Update developer guide and user guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CommandClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/CommandClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ug-application/AddApplication.png
  docs/images/ug-application/AddApplication1.png
  docs/images/ug-application/EditApplication.png
  docs/images/ug-application/EditApplication1.png
  docs/images/ug-application/FindApplication.png
  docs/images/ug-application/FindApplication1.png
  docs/images/ug-application/ViewApplication.png
  docs/images/ug-application/ViewApplication2.png
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/add/AddApplicationCommand.java
  src/main/java/seedu/address/logic/commands/add/AddCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteCommandAbstract.java
  src/main/java/seedu/address/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommandAbstract.java
  src/main/java/seedu/address/logic/commands/edit/EditInternshipCommand.java
  src/main/java/seedu/address/logic/commands/util/CommandUtil.java
  src/main/java/seedu/address/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/address/logic/parser/clisyntax/GeneralCliSyntax.java
  src/main/java/seedu/address/logic/parser/delete/DeleteInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/edit/EditInternshipCommandParser.java
  src/main/java/seedu/address/logic/parser/util/ApplicationParserUtil.java
  src/main/java/seedu/address/logic/parser/util/GeneralParserUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: Developer Guide, User guide

#282 Add match command implementation to developer guide
  docs/DeveloperGuide.md
  docs/diagrams/MatchCommandClassDiagram.puml
  docs/diagrams/MatchCommandSequenceDiagram.puml
  docs/images/MatchCommandClassDiagram.png
  docs/images/MatchCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/MatchCommand.java
Labels: Developer Guide, priority.High

#283 Update ugdg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/images/ug-profile/skills.png
Labels: Developer Guide

#288 Developer guide
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
Labels: Developer Guide, priority.High

#285 User guide update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ug-application/MatchCommand2.png
  docs/images/ug-general/match-internships1.png
  docs/images/ug-general/match-skills1.png
  docs/images/ug-general/match-type1.png
  docs/images/ug-general/match-window.png
  docs/index.md
Labels: User guide

#291 Update ug
  docs/UserGuide.md
  docs/images/AnnotatedGui.png
  docs/images/GuiAnnotated.png
  docs/images/ug-general/clear.png
  docs/images/ug-general/clearResult.png
  docs/images/ug-general/exit.png
  docs/images/ug-general/exitResult.png
  docs/images/ug-general/help.png
  docs/images/ug-general/helpResult.png
  docs/images/ug-general/switchApp.png
  docs/images/ug-general/switchAppResultAnnotated.png
Labels: User guide, priority.High

#293 Update User Stories and add Model diagram to DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CompanyInternshipApplicationClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ProfileClassDiagram.puml
  docs/images/dg-company/DeleteCompanyCommandClassDiagram.png
  docs/images/dg-company/DeleteCompanyCommandSequenceDiagram.png
  docs/images/dg-company/ExecuteDeleteCompany3CommandSequenceDiagram.png
  docs/images/dg-model/CompanyInternshipApplicationClassDiagram.png
  docs/images/dg-model/ModelClassDiagram.png
  docs/images/dg-model/ProfileClassDiagram.png
Labels: Developer Guide, priority.High

#298 Add more test cases
  src/main/java/seedu/internhunter/commons/exceptions/IllegalValueException.java
  src/main/java/seedu/internhunter/logic/parser/exceptions/ParseException.java
  src/main/java/seedu/internhunter/ui/display/DisplayKeyList.java
  src/test/java/seedu/internhunter/commons/util/FileUtilTest.java
  src/test/java/seedu/internhunter/logic/commands/CommandResultTest.java
  src/test/java/seedu/internhunter/logic/commands/util/CommandUtilTest.java
Labels: type.Task

#332 Fix list, view, find messages.
  src/main/java/seedu/internhunter/commons/core/Messages.java
  src/main/java/seedu/internhunter/logic/parser/find/FindCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/list/ListCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/view/ViewCommandParser.java
  src/test/java/seedu/internhunter/logic/commands/find/FindApplicationCommandTest.java
  src/test/java/seedu/internhunter/logic/parser/MainParserTest.java
  src/test/java/seedu/internhunter/model/UserPrefsTest.java
Labels: Code, type.bug

#333 User guide update
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/MatchCommandSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/MatchCommandSequenceDiagram.png
  src/main/java/seedu/internhunter/commons/core/Messages.java
  src/main/java/seedu/internhunter/logic/commands/MatchCommand.java
  src/main/java/seedu/internhunter/model/application/StatusDate.java
  src/main/java/seedu/internhunter/model/internship/InternshipItem.java
  src/main/java/seedu/internhunter/model/internship/Wage.java
  src/test/java/seedu/internhunter/model/internship/WageTest.java
Labels: Code, Developer Guide, User guide

#334 Enhancement
  src/main/java/seedu/internhunter/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/internhunter/ui/CommandBox.java
Labels: Code, type.Enhancement
