Repository AY2021S1-CS2103T-T15-4/tp, pull requests merged in 2020-11, with the labels that each got.

#339 User guide update for application section
  docs/UserGuide.md
  docs/images/ug-application/ApplicationAnnotated.png
  docs/images/ug-application/DeleteApplication.png
  docs/images/ug-application/ListApplication.png
Labels: User guide

#335 Update Developer Guide bugs
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/images/ArchitectureDiagram.png
Labels: Developer Guide

#342 Update images in Developer guide v1.4
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/MatchCommandClassDiagram.puml
  docs/diagrams/MatchCommandSequenceDiagram.puml
  docs/diagrams/MatchExecutionSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/DeleteSequenceDiagram1.png
  docs/images/LogicClassDiagram.png
  docs/images/MatchCommandClassDiagram.png
  docs/images/MatchCommandSequenceDiagram.png
  docs/images/MatchCommandSequenceDiagram1.png
  docs/images/MatchExecutionSequenceDiagram.png
  src/main/java/seedu/internhunter/logic/parser/delete/DeleteCommandParser.java
Labels: Developer Guide

#347 Readd codecov to workflow
  .github/workflows/gradle.yml
Labels: priority.High

#351 Resize pictures in developer guide and simplify diagram
  docs/DeveloperGuide.md
  docs/diagrams/MatchCommandClassDiagram.puml
  docs/images/MatchCommandClassDiagram.png
Labels: Developer Guide

#350 Update AddInternship parser
  src/main/java/seedu/internhunter/logic/commands/add/AddInternshipCommand.java
  src/main/java/seedu/internhunter/logic/parser/add/AddInternshipCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/add/AddProfileCommandParser.java
  src/main/java/seedu/internhunter/model/profile/ProfileItemCategory.java
Labels: type.Task

#352 Add tests for Profile Commands
  src/main/java/seedu/internhunter/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/internhunter/logic/parser/util/ProfileParserUtil.java
  src/main/java/seedu/internhunter/model/ModelManager.java
  src/main/java/seedu/internhunter/model/profile/ProfileItem.java
  src/main/java/seedu/internhunter/model/profile/ProfileItemCategory.java
  src/main/java/seedu/internhunter/model/util/ProfileItemCategoryUtil.java
  src/main/java/seedu/internhunter/model/util/ProfileItemUtil.java
  src/test/data/JsonSerializableProfileItemListTest/sampleProfileItemList.json
  src/test/java/seedu/internhunter/logic/commands/add/AddInternshipCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/add/AddProfileCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/add/ModelStub.java
  src/test/java/seedu/internhunter/logic/commands/delete/DeleteApplicationCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/delete/DeleteProfileCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditProfileCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/util/profile/EditProfileItemDescriptorBuilder.java
  src/test/java/seedu/internhunter/logic/commands/util/profile/ProfileCommandTestUtil.java
  src/test/java/seedu/internhunter/logic/parser/add/AddProfileCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/delete/DeleteProfileCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/edit/EditProfileCommandParserTest.java
  src/test/java/seedu/internhunter/model/profile/DescriptorTest.java
  src/test/java/seedu/internhunter/model/profile/ProfileItemCategoryTest.java
  src/test/java/seedu/internhunter/model/profile/ProfileItemTest.java
  src/test/java/seedu/internhunter/model/profile/TitleTest.java
  src/test/java/seedu/internhunter/storage/profile/JsonAdaptedProfileItemTest.java
  src/test/java/seedu/internhunter/testutil/profile/ProfileItemBuilder.java
  src/test/java/seedu/internhunter/testutil/profile/ProfileItemFieldsUtil.java
  src/test/java/seedu/internhunter/testutil/profile/SampleProfileItems.java
Labels: type.Task

#353 Update ugdg and include some test cases
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GetCommandResultSequenceDiagram.puml
  docs/diagrams/GetDeleteCommandResultSequenceDiagram.puml
  docs/diagrams/HandleDeleteDisplaySwitchIndexSequenceDiagram.puml
  docs/diagrams/SwitchCommandSequenceDiagram.puml
  docs/images/AnnotatedGui.png
  docs/images/GetCommandResultSequenceDiagram.png
  docs/images/GetDeleteCommandResultSequenceDiagram.png
  docs/images/HandleDeleteDisplaySwitchIndexSequenceDiagram.png
  docs/images/Ui.png
  docs/images/readme/App.png
  docs/images/readme/Profile.png
  docs/images/switchcommand/SwitchCommandSequenceDiagram.png
  docs/images/tempimg.png
  docs/images/ug-general/clear.png
  docs/images/ug-general/clearResult.png
  docs/images/ug-general/exit.png
  docs/images/ug-general/exitResult.png
  docs/images/ug-general/help.png
  docs/images/ug-general/helpResult.png
  docs/images/ug-general/switchApp.png
  docs/images/ug-general/switchAppResultAnnotated.png
  src/main/java/seedu/internhunter/model/application/ApplicationItem.java
  src/main/java/seedu/internhunter/ui/display/ApplicationDisplay.java
  src/main/java/seedu/internhunter/ui/display/CompanyDisplay.java
  src/main/java/seedu/internhunter/ui/display/ProfileDisplay.java
  src/test/java/seedu/internhunter/logic/commands/util/CommandUtilTest.java
  src/test/java/seedu/internhunter/model/ModelManagerTest.java
  src/test/java/seedu/internhunter/model/item/ItemListTest.java
  src/test/java/seedu/internhunter/model/item/UniqueItemListTest.java
  src/test/java/seedu/internhunter/testutil/application/SampleApplicationItems.java
  src/test/java/seedu/internhunter/testutil/company/CompanyItemFieldsUtil.java
  src/test/java/seedu/internhunter/testutil/company/SampleCompanyItems.java
  src/test/java/seedu/internhunter/testutil/profile/SampleProfileItems.java
  src/test/java/seedu/internhunter/ui/GuardClauseUiTest.java
Labels: Code, Developer Guide, User guide

#355 Add tests for match command and item list
  src/main/java/seedu/internhunter/logic/commands/CommandResult.java
  src/main/java/seedu/internhunter/model/internship/InternshipItem.java
  src/test/data/JsonSerializableApplicationItemListTest/sampleApplicationItemList.json
  src/test/data/JsonSerializableCompanyItemListTest/sampleCompanyItemList.json
  src/test/data/JsonSerializableProfileItemListTest/sampleProfileItemList.json
  src/test/java/seedu/internhunter/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/MatchCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/add/AddApplicationCommandTest.java
  src/test/java/seedu/internhunter/model/internship/InternshipItemTest.java
  src/test/java/seedu/internhunter/model/item/ItemListTest.java
  src/test/java/seedu/internhunter/model/item/UniqueItemListTest.java
  src/test/java/seedu/internhunter/testutil/internship/InternshipItemFieldsUtil.java
  src/test/java/seedu/internhunter/testutil/internship/SampleInternshipItems.java
  src/test/java/seedu/internhunter/testutil/profile/ProfileItemFieldsUtil.java
  src/test/java/seedu/internhunter/testutil/profile/SampleProfileItems.java
Labels: Code

#356 add parser test
  src/test/java/seedu/internhunter/MainAppUtilTest.java
  src/test/java/seedu/internhunter/logic/parser/add/AddCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/delete/DeleteCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/delete/DeleteCompanyCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/find/FindCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/find/FindCompanyCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/list/ListCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/view/ViewCompanyCommandParserTest.java
Labels: Code

#358 Add PPP and change Company's weaker notion of equality condition
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/shawn-nyk.md
  src/main/java/seedu/internhunter/model/company/CompanyItem.java
  src/test/java/seedu/internhunter/model/company/CompanyItemTest.java
Labels: priority.High, type.Task

#364 Update PPP
  docs/team/orzymandias.md
Labels: type.Task

#363 Add Effort section of Developer guide
  docs/DeveloperGuide.md
Labels: Developer Guide

#366 Add ppp
  codecov.yml
  docs/team/keanecjy.md
  src/main/java/seedu/internhunter/logic/parser/clisyntax/GeneralCliSyntax.java
Labels: priority.High, type.Task

#370 Update ppp
  docs/DeveloperGuide.md
  docs/team/seanjyjy.md
  src/main/java/seedu/internhunter/logic/commands/edit/EditApplicationCommand.java
  src/main/java/seedu/internhunter/logic/commands/edit/EditCompanyCommand.java
  src/main/java/seedu/internhunter/logic/commands/edit/EditProfileCommand.java
  src/main/java/seedu/internhunter/logic/commands/util/CommandUtil.java
  src/main/java/seedu/internhunter/logic/parser/util/GeneralParserUtil.java
  src/main/java/seedu/internhunter/model/ItemListManager.java
  src/main/java/seedu/internhunter/model/Model.java
  src/main/resources/view/Card.fxml
  src/main/resources/view/InformationDisplay.fxml
  src/main/resources/view/MainWindow.css
  src/test/java/seedu/internhunter/MainAppUtilTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditApplicationCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditCompanyCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditProfileCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/util/CommandUtilTest.java
  src/test/java/seedu/internhunter/model/ModelManagerTest.java
Labels: Code, Developer Guide

#373 Update UG for v1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteCompanyCommandClassDiagram.puml
  docs/images/AddCompanySS.PNG
  docs/images/EditCompanySS.PNG
  docs/images/ViewComSS.PNG
  docs/images/dg-company/DeleteCompanyCommandClassDiagram.png
  docs/images/ug-company/AddCompany.png
  docs/images/ug-company/AfterDelete.PNG
  docs/images/ug-company/BeforeDelete.PNG
  docs/images/ug-company/DeleteCom.png
  docs/images/ug-company/EditCom.png
  docs/images/ug-company/EditComExecuted.PNG
  docs/images/ug-company/FindComGoogleFacebookSS.png
  docs/images/ug-company/FindComGoogleSS.png
  docs/images/ug-company/GeneralStep1.PNG
  docs/images/ug-company/GeneralStep1MarkUp.png
  docs/images/ug-company/GeneralStep2.PNG
  docs/images/ug-company/GeneralStep2MarkUp.png
  docs/images/ug-company/ListCom.png
  docs/images/ug-company/ViewCom.png
  docs/images/ug-company/ViewCom1.PNG
  docs/images/ug-company/ViewCom2.PNG
Labels: User guide

#374 Add javadocs
  docs/team/keanecjy.md
  src/main/java/seedu/internhunter/logic/commands/Command.java
  src/main/java/seedu/internhunter/logic/commands/CommandResult.java
  src/main/java/seedu/internhunter/logic/commands/HelpCommand.java
  src/main/java/seedu/internhunter/logic/commands/MatchCommand.java
  src/main/java/seedu/internhunter/logic/commands/add/AddApplicationCommand.java
  src/main/java/seedu/internhunter/logic/commands/delete/DeleteApplicationCommand.java
  src/main/java/seedu/internhunter/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/internhunter/logic/commands/edit/EditApplicationCommand.java
  src/main/java/seedu/internhunter/logic/commands/edit/EditCommand.java
  src/main/java/seedu/internhunter/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/internhunter/logic/commands/util/CommandUtil.java
  src/main/java/seedu/internhunter/logic/commands/view/ViewApplicationCommand.java
  src/main/java/seedu/internhunter/logic/commands/view/ViewCommand.java
  src/main/java/seedu/internhunter/logic/commands/view/ViewCompanyCommand.java
  src/main/java/seedu/internhunter/logic/commands/view/ViewProfileCommand.java
  src/main/java/seedu/internhunter/logic/parser/Prefix.java
  src/main/java/seedu/internhunter/logic/parser/add/AddApplicationCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/clisyntax/ApplicationCliSyntax.java
  src/main/java/seedu/internhunter/logic/parser/edit/EditApplicationCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/edit/EditCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/util/GeneralParserUtil.java
  src/main/java/seedu/internhunter/logic/parser/view/ViewApplicationCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/view/ViewCommandParser.java
  src/main/java/seedu/internhunter/model/application/ApplicationItem.java
  src/main/java/seedu/internhunter/model/application/StatusDate.java
  src/main/java/seedu/internhunter/model/internship/InternshipItem.java
  src/main/java/seedu/internhunter/model/internship/Wage.java
  src/main/java/seedu/internhunter/model/internship/exceptions/InconsistentInternshipException.java
  src/main/java/seedu/internhunter/model/item/Item.java
  src/main/java/seedu/internhunter/model/item/ItemList.java
  src/main/java/seedu/internhunter/model/item/UniqueItemList.java
  src/main/java/seedu/internhunter/model/item/exceptions/DuplicateItemException.java
  src/main/java/seedu/internhunter/model/item/exceptions/ItemNotFoundException.java
  src/main/java/seedu/internhunter/model/wrapper/AlphaNumericWord.java
  src/main/java/seedu/internhunter/model/wrapper/NonEmptyString.java
  src/test/java/seedu/internhunter/model/item/UniqueItemListTest.java
  src/test/java/seedu/internhunter/testutil/application/ApplicationItemBuilder.java
Labels: Code

#392 Update ug and dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/HandleDeleteDisplaySwitchIndexSequenceDiagram.puml
  docs/images/HandleDeleteDisplaySwitchIndexSequenceDiagram.png
  src/main/java/seedu/internhunter/commons/core/index/Index.java
  src/main/java/seedu/internhunter/logic/commands/delete/DeleteInternshipCommand.java
  src/main/java/seedu/internhunter/logic/commands/util/CommandUtil.java
  src/main/java/seedu/internhunter/model/ModelManager.java
  src/main/resources/view/InformationDisplay.fxml
  src/test/java/seedu/internhunter/logic/commands/ClearCommandTest.java
Labels: Developer Guide, User guide

#394 Improve Code quality
  src/main/java/seedu/internhunter/commons/core/Version.java
  src/main/java/seedu/internhunter/logic/parser/ArgumentTokenizer.java
  src/test/java/seedu/internhunter/AppParametersTest.java
  src/test/java/seedu/internhunter/model/item/UniqueItemListTest.java
Labels: Code

#393 Update ug
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ug-application/ApplicationAnnotated.png
  docs/images/ug-application/ApplicationAnnotated1.png
  docs/images/ug-application/GeneralApplicationCommand01.png
  docs/images/ug-application/GeneralApplicationCommand02.png
  docs/images/ug-general/match-internships1.png
  docs/images/ug-general/match-skills.png
  docs/images/ug-general/match-skills1.png
  docs/images/ug-general/match-type.png
  docs/images/ug-general/match-type1.png
  docs/images/ug-general/match-window.png
  docs/images/ug-general/match-window1.png
  src/main/java/seedu/internhunter/MainAppUtil.java
  src/test/java/seedu/internhunter/commons/core/index/IndexTest.java
Labels: Developer Guide, User guide

#395 Update javadocs
  README.md
  src/main/java/seedu/internhunter/commons/core/index/Index.java
  src/main/java/seedu/internhunter/logic/Logic.java
  src/main/java/seedu/internhunter/logic/LogicManager.java
  src/main/java/seedu/internhunter/model/Model.java
  src/main/java/seedu/internhunter/model/ModelManager.java
  src/main/java/seedu/internhunter/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/internhunter/model/UserPrefs.java
  src/main/java/seedu/internhunter/ui/ResultDisplay.java
  src/main/java/seedu/internhunter/ui/Ui.java
  src/main/java/seedu/internhunter/ui/UiManager.java
  src/main/java/seedu/internhunter/ui/UiPart.java
  src/main/java/seedu/internhunter/ui/cards/ApplicationCard.java
  src/main/java/seedu/internhunter/ui/cards/Card.java
  src/main/java/seedu/internhunter/ui/cards/CompanyCard.java
  src/main/java/seedu/internhunter/ui/cards/InternshipCard.java
  src/main/java/seedu/internhunter/ui/cards/ProfileCard.java
  src/main/java/seedu/internhunter/ui/display/ApplicationDisplay.java
  src/main/java/seedu/internhunter/ui/display/CompanyDisplay.java
  src/main/java/seedu/internhunter/ui/display/ProfileDisplay.java
  src/main/java/seedu/internhunter/ui/textstyle/TitleDescription.java
  src/main/resources/view/MainWindow.css
  src/test/java/seedu/internhunter/commons/core/index/IndexTest.java
  src/test/java/seedu/internhunter/logic/commands/util/CommandUtilTest.java
Labels: Code

#396 Update User guide for 1.4
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/ug-profile/AddProfile.png
  docs/images/ug-profile/AddProfileItem.png
  docs/images/ug-profile/AddProfileItemSS.png
  docs/images/ug-profile/DeleteProfile.png
  docs/images/ug-profile/EditProfile.PNG
  docs/images/ug-profile/EditProfile.png
  docs/images/ug-profile/EditProfileItemAfterSS.png
  docs/images/ug-profile/EditProfileItemBeforeSS.png
  docs/images/ug-profile/GeneralStepProfile.png
  docs/images/ug-profile/GeneralStepProfileTwo.png
  docs/images/ug-profile/ListProfile.png
  docs/images/ug-profile/ProfileOverview.png
  docs/images/ug-profile/ViewProfile.png
  docs/images/ug-profile/ViewProfileAfterSS.png
  docs/images/ug-profile/ViewProfileBeforeSS.png
  docs/images/ug-profile/ViewProfileThree.png
Labels: User guide

#398 Add test for ui
  docs/team/keanecjy.md
  docs/team/seanjyjy.md
  src/main/java/seedu/internhunter/ui/cards/ApplicationCard.java
  src/main/java/seedu/internhunter/ui/cards/Card.java
  src/main/java/seedu/internhunter/ui/cards/CompanyCard.java
  src/main/java/seedu/internhunter/ui/cards/InternshipCard.java
  src/main/java/seedu/internhunter/ui/cards/ProfileCard.java
  src/test/java/seedu/internhunter/MainAppUtilTest.java
  src/test/java/seedu/internhunter/logic/LogicManagerTest.java
  src/test/java/seedu/internhunter/logic/commands/CommandResultTest.java
  src/test/java/seedu/internhunter/model/ModelManagerTest.java
  src/test/java/seedu/internhunter/model/item/ItemListTest.java
  src/test/java/seedu/internhunter/model/item/UniqueItemListTest.java
  src/test/java/seedu/internhunter/model/tab/TabManagerTest.java
  src/test/java/seedu/internhunter/model/view/ViewManagerTest.java
  src/test/java/seedu/internhunter/ui/CardTest.java
Labels: Code

#403 Add tests for match command
  src/test/java/seedu/internhunter/logic/commands/CommandResultTest.java
  src/test/java/seedu/internhunter/logic/commands/CommandTestUtil.java
  src/test/java/seedu/internhunter/logic/commands/MatchCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/delete/DeleteProfileCommandTest.java
Labels: Code

#402 Update user guide and developer guide
  docs/UserGuide.md
  docs/team/keanecjy.md
Labels: Developer Guide, User guide

#408 Update tests
  src/main/java/seedu/internhunter/model/internship/Wage.java
  src/test/java/seedu/internhunter/logic/commands/MatchCommandTest.java
  src/test/java/seedu/internhunter/logic/parser/edit/EditCommandParserTest.java
  src/test/java/seedu/internhunter/model/internship/InternshipItemTest.java
  src/test/java/seedu/internhunter/model/internship/JobTitleTest.java
  src/test/java/seedu/internhunter/model/internship/PeriodTest.java
  src/test/java/seedu/internhunter/model/internship/WageTest.java
  src/test/java/seedu/internhunter/model/wrapper/AlphaNumericWordTest.java
  src/test/java/seedu/internhunter/model/wrapper/NonEmptyStringTest.java
Labels: Code

#413 Update message for wage
  src/main/java/seedu/internhunter/model/internship/Wage.java
  src/test/java/seedu/internhunter/commons/util/ConfigUtilTest.java
Labels: Code

#409 Update ug dg and some code
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/seanjyjy.md
  src/main/java/seedu/internhunter/MainApp.java
  src/main/java/seedu/internhunter/logic/commands/CommandResult.java
  src/main/java/seedu/internhunter/logic/commands/SwitchCommand.java
  src/main/java/seedu/internhunter/logic/commands/edit/EditInternshipCommand.java
  src/main/java/seedu/internhunter/logic/parser/find/FindApplicationCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/find/FindCompanyCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/find/FindProfileCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/list/ListCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/switchparser/SwitchCommandParser.java
  src/main/java/seedu/internhunter/logic/parser/util/TabParserUtil.java
  src/main/java/seedu/internhunter/model/ItemListManager.java
  src/main/java/seedu/internhunter/model/profile/ProfileItem.java
  src/main/java/seedu/internhunter/model/tab/Tab.java
  src/main/java/seedu/internhunter/model/tab/TabManager.java
  src/main/java/seedu/internhunter/model/view/View.java
  src/main/java/seedu/internhunter/model/view/ViewManager.java
  src/main/java/seedu/internhunter/ui/GuardClauseUi.java
  src/main/java/seedu/internhunter/ui/MainWindow.java
  src/main/java/seedu/internhunter/ui/cards/ApplicationCard.java
  src/main/java/seedu/internhunter/ui/cards/Card.java
  src/main/java/seedu/internhunter/ui/cards/CompanyCard.java
  src/main/java/seedu/internhunter/ui/cards/InternshipCard.java
  src/main/java/seedu/internhunter/ui/cards/ProfileCard.java
  src/main/java/seedu/internhunter/ui/display/ApplicationDisplay.java
  src/main/java/seedu/internhunter/ui/display/CompanyDisplay.java
  src/main/java/seedu/internhunter/ui/display/ProfileDisplay.java
  src/main/java/seedu/internhunter/ui/tabs/Tabs.java
  src/test/java/seedu/internhunter/commons/util/JsonUtilTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditCompanyCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditCompanyDescriptorTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditProfileCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditProfileDescriptorTest.java
  src/test/java/seedu/internhunter/logic/commands/util/CommandUtilTest.java
  src/test/java/seedu/internhunter/logic/commands/util/company/SampleEditCompanyDescriptor.java
  src/test/java/seedu/internhunter/logic/commands/util/profile/SampleEditProfileDescriptor.java
  src/test/java/seedu/internhunter/logic/parser/PrefixTest.java
  src/test/java/seedu/internhunter/model/profile/ProfileItemTest.java
  src/test/java/seedu/internhunter/storage/StorageManagerTest.java
  src/test/java/seedu/internhunter/ui/CardTest.java
  src/test/java/seedu/internhunter/ui/TitleDescriptionTest.java
Labels: Code, Developer Guide, User guide

#419 Update UG, DG and PPP
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/CompanyInternshipApplicationClassDiagram.puml
  docs/diagrams/ExecuteDeleteCompany3CommandSequenceDiagram.puml
  docs/images/dg-company/ExecuteDeleteCompany3CommandSequenceDiagram.png
  docs/images/dg-model/CompanyInternshipApplicationClassDiagram.png
  docs/team/shawn-nyk.md
Labels: Developer Guide, User guide, priority.High

#418 Add JUnit tests
  src/test/java/seedu/internhunter/logic/commands/edit/EditInternshipCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/find/FindApplicationCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/find/FindCompanyCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/list/ListApplicationCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/list/ListCompanyCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/list/ListProfileCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/util/company/CompanyCommandTestUtil.java
  src/test/java/seedu/internhunter/logic/commands/util/internship/EditInternshipDescriptorBuilder.java
  src/test/java/seedu/internhunter/logic/commands/util/internship/InternshipCommandTestUtil.java
  src/test/java/seedu/internhunter/logic/parser/add/AddCompanyCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/edit/EditCompanyCommandParserTest.java
  src/test/java/seedu/internhunter/logic/parser/edit/EditInternshipCommandParserTest.java
  src/test/java/seedu/internhunter/testutil/company/CompanyItemFieldsUtil.java
Labels: priority.High

#422 Add more JUnit test
  docs/UserGuide.md
  docs/team/seanjyjy.md
  src/test/java/seedu/internhunter/commons/core/ConfigTest.java
  src/test/java/seedu/internhunter/commons/core/GuiSettingsTest.java
  src/test/java/seedu/internhunter/commons/core/VersionTest.java
  src/test/java/seedu/internhunter/logic/commands/add/AddInternshipCommandTest.java
  src/test/java/seedu/internhunter/logic/commands/edit/EditInternshipCommandTest.java
  src/test/java/seedu/internhunter/model/ModelManagerTest.java
  src/test/java/seedu/internhunter/model/UserPrefsTest.java
  src/test/java/seedu/internhunter/storage/application/JsonAdaptedApplicationItemTest.java
  src/test/java/seedu/internhunter/storage/company/JsonAdaptedCompanyItemTest.java
  src/test/java/seedu/internhunter/storage/internship/JsonAdaptedInternshipItemTest.java
  src/test/java/seedu/internhunter/storage/profile/JsonAdaptedProfileItemTest.java
Labels: Code

#429 Add page breaks for user guide
  docs/UserGuide.md
Labels: User guide

#428 update test that are partially hit
  src/test/java/seedu/internhunter/commons/util/FileUtilTest.java
  src/test/java/seedu/internhunter/commons/util/StringUtilTest.java
  src/test/java/seedu/internhunter/logic/commands/add/AddInternshipCommandTest.java
  src/test/java/seedu/internhunter/model/application/StatusDateTest.java
  src/test/java/seedu/internhunter/model/company/CompanyNameTest.java
  src/test/java/seedu/internhunter/model/company/EmailTest.java
  src/test/java/seedu/internhunter/model/company/IndustryTest.java
  src/test/java/seedu/internhunter/model/company/PhoneTest.java
  src/test/java/seedu/internhunter/model/internship/JobTitleTest.java
  src/test/java/seedu/internhunter/model/internship/PeriodTest.java
  src/test/java/seedu/internhunter/model/internship/RequirementTest.java
  src/test/java/seedu/internhunter/storage/application/JsonAdaptedApplicationItemTest.java
  src/test/java/seedu/internhunter/storage/company/JsonAdaptedCompanyItemTest.java
  src/test/java/seedu/internhunter/storage/internship/JsonAdaptedInternshipItemTest.java
  src/test/java/seedu/internhunter/storage/profile/JsonAdaptedProfileItemTest.java
Labels: Code

#430 Update quick start in user guide
  docs/UserGuide.md
Labels: User guide
